name: Build, Tag, and Deploy to JitPack

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Manually install OpenJDK 23 from Adoptium
      - name: Set up OpenJDK 23
        run: |
          # Download and install OpenJDK 23 from Adoptium
          wget https://github.com/adoptium/temurin23-binaries/releases/download/jdk-23+36/OpenJDK23U-jdk_x64_linux_23_36.tar.gz
          tar -xvf OpenJDK23U-jdk_x64_linux_23_36.tar.gz
          sudo mv jdk-23 /opt/
          sudo update-alternatives --install /usr/bin/java java /opt/jdk-23/bin/java 1
          sudo update-alternatives --set java /opt/jdk-23/bin/java
          java -version  # Verify the installation

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '7.2'

      # Build the Kotlin project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Optionally: Run tests with Gradle
      - name: Run tests with Gradle
        run: ./gradlew test

  tag_and_release:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Increment version and create a tag
      - name: Create a new Git tag
        id: create_tag
        run: |
          # Increment the version (you can adjust this logic)
          VERSION=$(date +'%Y.%m.%d.%H%M%S')  # Create a version based on date for simplicity
          git tag "v$VERSION"
          echo "v$VERSION" > version.txt
          git push origin "v$VERSION"  # Push the tag to GitHub

      # Create a GitHub release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: version.txt  # Attach version info or any other files you need
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
